# Generated by Django 4.1.1 on 2022-09-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucking_app', '0004_alter_dispatch_pod'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='packages',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipper',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.CharField(default='', max_length=20),
        ),
    ]
